### PR TITLE
Crypt and influance out

### PR DESCRIPTION
**Pull request by mtwarowski**

### CODE REVIEW

**Comment by mtwarowski** [comment]
@lionel-panhaleux  basic change to add vampire and "flip / turn" it. This we need to do some background work to move the state of those Pixi objects to a gameState class or something instead of using a global functions. 

Also there seem to be an issue with scale functions on a menu that you added. When i change the texture on a card the icon get bigger and smaller

**Comment by lionel-panhaleux** [comment]
So, I tested it locally, and I got three bugs:
1. When adding a crypt card, the current card selection is not reset and the crypt card is added to it, I think it should be reset.
2. The radial menu size is not correct (either too big or too small).
3. When flipping a crypt card for the first time, it does not flip correctly, until it was locked/unlocked first.

And I'd say that having a flip button alongside the lock/unlock button would make more sense than having it underneath the table.

**Comment by mtwarowski** [comment]
Small update with new menu proposition. Enjoy! @lionel-panhaleux @Ajikozau

**Comment by wikett** [comment]
I have updated this branch, using the new radial menu to add and remove blood. Purple button to add blood and cyan button to remove blood

**Comment by mtwarowski** [comment]
Hey @wikett thanks for doing it. Only thing is there seems to be an issue with that blood icon when the card is flipped. The bood looks way to big. Have a look:

image

**Comment by mtwarowski** [comment]
@lionel-panhaleux added an icon for tap. Have a look

**Comment by mtwarowski** [comment]
Also with the blood display. I'm not a designer so i might be wrong but i think it might be cool to move that blood indicator right on the capacity of the vampire. What do you guys think?

**Comment by wikett** [comment]
> Also with the blood display. I'm not a designer so i might be wrong but i think it might be cool to move that blood indicator right on the capacity of the vampire. What do you guys think?

I don't think is a good idea. Sometime during the game you must know the capacity of the vampire to play one card

**Comment by wikett** [comment]
> Hey @wikett thanks for doing it. Only thing is there seems to be an issue with that blood icon when the card is flipped. The bood looks way to big. Have a look:
> 
> image

Fixed and added more vampires to the uncontrolled region ;)

**Comment by mtwarowski** [comment]
@wikett  I think we still need to see the bood on face down cards

**Comment by wikett** [comment]
> @wikett I think we still need to see the bood on face down cards

Fixed. I have added crypt facedown texture (just for testing) to see working.

**Comment by mtwarowski** [comment]
Looks good to me. @lionel-panhaleux shell i merge?

**Pull request merged**
